# TODO(Matthias): review and see which exception we can remove over time.
# Eg removing syn is blocked by ark-ff-asm cutting a new release
# (https://github.com/arkworks-rs/algebra/issues/813) amongst other things.
allowed-duplicate-crates = [
  "hashbrown",
  "itertools",
  "regex-automata",
  "regex-syntax",
  "syn",
  "thiserror",
  "thiserror-impl",
  "windows-sys",
  "tracing-subscriber",
  "wasi",
  "getrandom",
  "zerocopy",
  "zerocopy-derive",
  "proc-macro-crate",
  "toml_edit",
  "toml_datetime",
  "winnow",
  "generic-array",
  "num-bigint",
]
